services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORTAINER_API_URL=${PORTAINER_API_URL}
      - PORTAINER_API_TOKEN=${PORTAINER_API_TOKEN}
    ports:
      - "5000:5000"
    networks:
      - mc-server-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3007:3000"  # Map host port 3007 to container port 3000
    networks:
      - mc-server-net
    restart: unless-stopped

networks:
  mc-server-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
